// Register chart.js components once for the whole dashboard.
import {
  Chart as ChartJS,
  ArcElement,
  BarController,
  BarElement,
  CategoryScale,
  Filler,
  LineController,
  LineElement,
  LinearScale,
  PointElement,
  PolarAreaController,
  RadialLinearScale,
  ScatterController,
  Tooltip,
  Legend,
} from "chart.js";

ChartJS.register(
  ArcElement,
  BarController,
  BarElement,
  CategoryScale,
  Filler,
  LineController,
  LineElement,
  LinearScale,
  PointElement,
  PolarAreaController,
  RadialLinearScale,
  ScatterController,
  Tooltip,
  Legend,
);

export const FORMA_CHART_COLORS = {
  ink: "#F0F0F0",
  ink2: "#A0A0A0",
  ink3: "#666666",
  ink4: "#444444",
  gold: "#AEE710",
  goldSoft: "#C2F04A",
  orange: "#AEE710",
  good: "#4ADE80",
  warn: "#FBBF24",
  bad: "#F87171",
  rule: "rgba(255,255,255,0.08)",
  ruleStrong: "rgba(255,255,255,0.16)",
};
